name: Hello world workflow

on:
  push:
    branches:
      - feature/test_workflow
  pull_request:
    branches:
      - feature/test_workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
  goodbye: 
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye"
        shell: bash
