name: Frontend pipeline

on:
  push:
    branches: [ "development", "feature/**" ]
  pull_request:
    branches: [ "development", "feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          projectBaseDir: ${{ github.workspace }}/src/
          args:
            -Dsonar.projectKey=De-Oefenpraktijk_Frontend
            -Dsonar.organization=de-oefenpraktijk
  
  End_to_end:
    runs-on: ubuntu-latest

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Print CYPRESS_RECORD_KEY
        run: echo $CYPRESS_RECORD_KEY
      
      - name: Check path content
        run: ls ${{ github.workspace }}
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          config-file: cypress.config.js
          # spec: ${{ github.workspace }}/cypress_test.js
          headless: true
